export const SECONDS_IN_DAY = 24 * 60 * 60;
export const SECONDS_IN_HOUR = 60 * 60;
export const DAY_LABEL_CELLS_SIZE = 1;
export const CELL_BORDER_WIDTH = '1px';
export const DAY_LABEL_WIDTH_PERCENT = (DAY_LABEL_CELLS_SIZE * SECONDS_IN_HOUR) * 100 / SECONDS_IN_DAY;